---
title: "Data Approach and Methods"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(expss)
library(devtools)
library(quantmod)
library(lubridate)
library(tidyverse)
library(readr)

```

## Data Approaches for Auto Manufacturing 

```{r data, echo=FALSE}
#### Nissan Automobile Sales Forecast Model ####

#### Set Up Work Directory Enviornment ####


AISRSA <- read.csv('https://raw.githubusercontent.com/ttownsley/Research-Methods-Automotive/master/Data%20Sets/AISRSA.csv')



data <- read_csv("https://raw.githubusercontent.com/ttownsley/Research-Methods-Automotive/master/Data%20Sets/AISRSA.csv")
#### Import Data ####

# Automobile Inventory Sales Ratio (in ______), Seasonally Adjusted
aisrsa <- 
  read.csv('https://raw.githubusercontent.com/ttownsley/Research-Methods-Automotive/master/Data%20Sets/AISRSA.csv')

# Domestic Automobile Inventories (in _____), Seasonally Adjusted
auinsa <- 
  read.csv('https://raw.githubusercontent.com/ttownsley/Research-Methods-Automotive/master/Data%20Sets/AUINSA.csv')

# Domestic Automobile Production (in _____), Seasonally Adjusted
daupsa <- 
  read.csv('https://raw.githubusercontent.com/ttownsley/Research-Methods-Automotive/master/Data%20Sets/DAUPSA.csv')

# Domestic Automobile Production (in _____), Not DSeasonally Adjusted
daupnsa <- 
  read.csv('https://raw.githubusercontent.com/ttownsley/Research-Methods-Automotive/master/Data%20Sets/DAUPNSA.csv')

# Mexican Automobile Imports (in thousands), Seasonally Adjusted
mauisa <- 
  read.csv('https://raw.githubusercontent.com/ttownsley/Research-Methods-Automotive/master/Data%20Sets/MAUISA.csv')

# Mexican Automobile Imports (in thousands), Not Seasonally Adjusted
mauinsa <- 
  read.csv('https://raw.githubusercontent.com/ttownsley/Research-Methods-Automotive/master/Data%20Sets/MAUINSA.csv')

# Domestic Motor Vehicle Retail Sales ( in ____), Seasonally Adjusted
mauinsa <- 
  read.csv('https://raw.githubusercontent.com/ttownsley/Research-Methods-Automotive/master/Data%20Sets/DAUTOSA.csv')
  
# Domestic Motor Vehicle Retail Sales ( in ____), Not Seasonally Adjusted
dautonsa <- 
  read.csv('https://raw.githubusercontent.com/ttownsley/Research-Methods-Automotive/master/Data%20Sets/DAUTONSA.csv')

# Industrial Production Index & Vehicle Parts
ipd <- 
  read.csv('https://raw.githubusercontent.com/ttownsley/Research-Methods-Automotive/master/Data%20Sets/IPD.csv')

# Domestic & Foreign Motor Vehicle Retail Sales (in ____), Not Seasonally Adjusted
lautonsa  <- 
  read.csv('https://raw.githubusercontent.com/ttownsley/Research-Methods-Automotive/master/Data%20Sets/LAUTONSA.csv')

# Motor Vehicle Retail Sales, Foreign Autos (in thousands), Seasonally Adjusted
fautosa <- 
  read.csv('https://raw.githubusercontent.com/ttownsley/Research-Methods-Automotive/master/Data%20Sets/FAUTOSA.csv')

# Motor Vehicle Retail Sales, Foreign Autos (in thousands), Not Seasonally Adjusted
fautonsa <- 
  read.csv('https://raw.githubusercontent.com/ttownsley/Research-Methods-Automotive/master/Data%20Sets/FAUTONSA.csv')

# Retail Sales Used Car Dealers
mrtss <- 
  read.csv('https://raw.githubusercontent.com/ttownsley/Research-Methods-Automotive/master/Data%20Sets/MRTSS.csv')

# Total Industry Car Sales (in ), Seasonally Adjusted
totalsa <- 
  read.csv('https://raw.githubusercontent.com/ttownsley/Research-Methods-Automotive/master/Data%20Sets/TOTALSA.csv')

# Total Industry Car Sales (in ), Not Seasonally Adjusted
totalnsa <- 
  read.csv('https://raw.githubusercontent.com/ttownsley/Research-Methods-Automotive/master/Data%20Sets/TOTALNSA.csv')

# Advance Retail Sales of Vehicle Parts Dealers (in millions)
rsmvpd <- 
  read.csv('https://raw.githubusercontent.com/ttownsley/Research-Methods-Automotive/master/Data%20Sets/RSMVPD.csv')

cbind(aisrsa, auinsa)


```

## Preliminary Time Plots

Looking first as at plots of Total Industry Car Sales, Seasonally Adjusted: 

```{r cars sales, echo=FALSE}
### Exploratory Analysis ###

## creates time series object from data sets ## see https://otexts.com/fpp2/ts-objects.html

timeSA <- ts(totalsa, frequency = 12,  start = c(1976, 1))
plot(timeSA)



```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
